package cli

import (
	"bytes"
	"fmt"
	"os"
	"strings"

	"github.com/MohamedElashri/sanad/internal/policy"
)

func writePlanPRBody(path string, report planReport) error {
	data := append(renderPlanPRBody(report), '\n')
	if err := os.WriteFile(path, data, 0o600); err != nil {
		return fmt.Errorf("write pull request body %q: %w", path, err)
	}
	return nil
}

func renderPlanPRBody(report planReport) []byte {
	var out bytes.Buffer
	_, _ = fmt.Fprintln(&out, "# Update pinned GitHub Actions")
	_, _ = fmt.Fprintln(&out)
	_, _ = fmt.Fprintln(&out, "Generated by `sanad plan`.")
	_, _ = fmt.Fprintln(&out)
	_, _ = fmt.Fprintln(&out, "## Summary")
	_, _ = fmt.Fprintf(&out, "- Actions found: %d\n", report.Summary.Actions)
	_, _ = fmt.Fprintf(&out, "- Already pinned: %d\n", report.Summary.AlreadyPinned)
	_, _ = fmt.Fprintf(&out, "- Updates available: %d\n", report.Summary.UpdatesAvailable)
	_, _ = fmt.Fprintf(&out, "- Pending cooldown: %d\n", report.Summary.PendingCooldown)
	_, _ = fmt.Fprintf(&out, "- Policy violations: %d\n", report.Summary.PolicyViolations)
	_, _ = fmt.Fprintf(&out, "- Skipped: %d\n", report.Summary.Skipped)
	_, _ = fmt.Fprintln(&out)

	writePRBodySection(&out, "Updates", report, func(action planAction) bool {
		return action.Decision == policy.DecisionUpdate
	})
	writePRBodySection(&out, "Pending Cooldown", report, func(action planAction) bool {
		return action.Decision == policy.DecisionPending
	})
	writePRBodySection(&out, "Policy Violations", report, func(action planAction) bool {
		return isBlockingDecision(action.Decision)
	})
	return out.Bytes()
}

func writePRBodySection(out *bytes.Buffer, title string, report planReport, include func(planAction) bool) {
	rows := prBodyRows(report, include)
	_, _ = fmt.Fprintf(out, "## %s\n", title)
	if len(rows) == 0 {
		_, _ = fmt.Fprintln(out, "None.")
		_, _ = fmt.Fprintln(out)
		return
	}

	_, _ = fmt.Fprintln(out, "| File | Line | Action | Ref | Current | Candidate | Decision |")
	_, _ = fmt.Fprintln(out, "| --- | ---: | --- | --- | --- | --- | --- |")
	for _, row := range rows {
		_, _ = fmt.Fprintf(
			out,
			"| %s | %d | %s | %s | %s | %s | %s |\n",
			escapeMarkdownTable(row.File),
			row.Line,
			escapeMarkdownTable(row.Action),
			escapeMarkdownTable(emptyDash(row.Ref)),
			escapeMarkdownTable(shortSHAOrDash(row.CurrentSHA)),
			escapeMarkdownTable(shortSHAOrDash(row.CandidateSHA)),
			escapeMarkdownTable(string(row.Decision)),
		)
	}
	_, _ = fmt.Fprintln(out)
}

type prBodyRow struct {
	File         string
	Line         int
	Action       string
	Ref          string
	CurrentSHA   string
	CandidateSHA string
	Decision     policy.DecisionKind
}

func prBodyRows(report planReport, include func(planAction) bool) []prBodyRow {
	var rows []prBodyRow
	for _, file := range report.Files {
		for _, action := range file.Actions {
			if !include(action) {
				continue
			}
			rows = append(rows, prBodyRow{
				File:         file.Path,
				Line:         action.Line,
				Action:       planActionName(action),
				Ref:          action.LogicalRef,
				CurrentSHA:   action.CurrentSHA,
				CandidateSHA: action.CandidateSHA,
				Decision:     action.Decision,
			})
		}
	}
	return rows
}

func escapeMarkdownTable(value string) string {
	value = strings.ReplaceAll(value, `\`, `\\`)
	return strings.ReplaceAll(value, "|", `\|`)
}
